default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  s3_key: <%= ENV['S3_KEY'] %>
  s3_secret: <%= ENV['S3_SECRET'] %>
  asset_host: <%= ENV['ASSET_HOST'] %>
  devise_secret: <%= ENV['DEVISE_SECRET'] %>
  ga_service_account: <%= ENV['GA_SERVICE_ACCOUNT'] %>
  ga_property_id: <%= ENV['GA_PROPERTY_ID'] %>
  ga_profile_id: <%= ENV['GA_PROFILE_ID'] %>
  ga_private_key: "<%= ENV['GA_PRIVATE_KEY'] %>"

development:
  <<: *default
  secret_key_base: 7ad3934a4428d33cedae8c422c0d6e627de1375312ef05b867961b06e7bf3882ae4dcfe5418d6961a1d51afa4e7757c7f6b9bd4b8ece99895790b2065a94585c
  s3_bucket_name: tinypantry-development
  s3_key: AKIAI75GQLJVQWWAKPLA
  s3_secret: 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
  devise_secret: 15d79e81f90640f28a7dc2e73b29a5a511e24c57fdb7b8f879137bcb0bb3236e20cae0eb893a6566e72b5ea2381d4bb3d0260921626cb956dd5a43fbdb23d906
  ga_service_account: 383848500300-lm0c75i5jsth8lv1o36nou3fe3899l3s@developer.gserviceaccount.com
  ga_property_id: UA-41589871-3
  ga_profile_id: 89479413
  ga_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQCXJ3/Z5oOb+gaBfuaLG6GueCoN7TsqJDmPUnEe05JF8iaYhUs3
    pX2ycHNW4lfJSvkNkf7kfWkN1MTo4mO8TcUtq3iTejdvUw9Z7UZopvZ2uA5rghfw
    O7u5osByzIaP1EWiNUOMvCibMhzvJqKFA+cFxQE7jULzZWYx8D2EwVANBwIDAQAB
    AoGAZo77daqtc8CSd3zWCl7mNg38YtSrBy3rDC7g6Ayfu+vQej4+yfP0tIUODU6o
    R8Eh+S4tJ3VcOXE7ZdRt3Y9bEFXLMiciypgjzYWTzD9mgcv++Fb0zgh+/Dt4MzZ3
    809ve9pj1r+W09ODN27Uu8f6JZNcc4gt08l2YuIOFNuKgjkCQQDGZzZ/lbVdkbvD
    z71j00siNtANzoK4Sliob26nyNL8PzLZTzXWaGRYTGr00vnoB1ofsTFz4KwRq3iv
    VATrPo9bAkEAwwjgqKVAVF10eQfBDrKT89bhQl3KZvTt+7l2goF5TirV2PFAuvGS
    s/wI0fLakdqbWa0Oo0rqpeBK136UU+v0xQJBAKvK9TKWQ/uoU8giWiBU9arDgXVj
    Cmde4NO/4TXhO2d1pabq4ngr3i9iw/4HrKKPsybb/DEVKokGS7Ks8rFrcx8CQEWp
    +R0kEatQylak12eZj9FsMn/TIoXN/OeKInORLbQnBsV7vwRHX4BciQX8+edZL15D
    u1PGYbQoPnNkqjSjtoUCQGhJhNumCrUR19X2o40IvCxtoo86sJcHcRe7i5wXTUCE
    ZSMB3mcb1A7a9JxjXV+SON0sOuf4TquPKLHIUNu4KiA=
    -----END RSA PRIVATE KEY-----

test:
  secret_key_base: 5160887c3ba275984a512a5ae7a1a5270f4a5c9a5bc5f1063816bc9d6df4cbc6f67548eafc40907e141cd8d6a80096db7c4754afd8891da43580cb41b08460b5

production:
  <<: *default
